[build]
  base = "packages/client"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  # Configure secrets scanning to ignore documentation files and placeholders
  SECRETS_SCAN_OMIT_PATHS = "DEPLOYMENT_GUIDE.md,deploy-to-render.sh,deploy-to-netlify.sh,packages/server/src/index.ts,packages/server/src/services/aiService.ts"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add CORS headers for assets to allow them to be loaded in the preview iframe
[[headers]]
  for = "/assets/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
