[build]
  base = "packages/client"
  command = "npm install --no-audit --no-fund && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  # Increase memory for the Node.js process to prevent out-of-memory errors during build
  NODE_OPTIONS = "--max-old-space-size=3072"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200