[build]
  # Run commands from the monorepo root for proper dependency installation and build context.
  command = "npm install && npm run build --workspace=client"
  publish = "packages/client/dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  # Increase memory for the Node.js process to prevent out-of-memory errors during build
  NODE_OPTIONS = "--max-old-space-size=3072"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200