# render.yaml
# This file provides a definitive configuration for your backend service on Render.
# By using this, you ensure your deployment settings are version-controlled and consistent.

services:
  - type: web # Specifies this is a web service
    name: alt-ai-mate-backend # A name for your service in Render
    runtime: node # The runtime environment
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # ❗️ Replace with your actual GitHub repository URL
    branch: main # The branch to deploy from
    healthCheckPath: /api/health # The path Render uses to check if your app is live
    envVars:
      - key: NODE_VERSION
        value: 18.17.1 # Stable LTS version supported by Render
      - key: NODE_ENV
        value: production
      # ❗️ IMPORTANT: Add all your other environment variables from your local .env file here.
      # For secrets, you can add the key here and set the value in the Render dashboard.
      # - key: DATABASE_URL
      #   sync: false

    # --- Monorepo Settings ---
    buildCommand: "npm install && cd packages/server && npm install && npm run build" # Install root deps, then server deps, then build
    startCommand: "cd packages/server && npm start" # Runs the compiled server from the dist directory
