services:
  - type: web
    name: alt-ai-mate-backend
    runtime: node
    plan: free
    rootDir: packages/server
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000