services:
  - type: web
    name: alt-ai-mate-backend
    runtime: node
    plan: free
    buildCommand: cd packages/server && npm install && npm run build
    startCommand: cd packages/server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: "18.17.1"