const express = require('express');
const cors = require('cors');

const app = express();
const port = process.env.PORT || 3001;

// --- Middleware ---
// Request logging middleware
app.use((req, res, next) => {
  console.log(`${new Date().toISOString()} - ${req.method} ${req.originalUrl}`);
  next();
});

// Enable CORS for all routes to allow the frontend to connect
app.use(cors());
// Parse JSON bodies for API requests
app.use(express.json());

// --- API Routes ---

/**
 * @route   GET /api/health
 * @desc    Health check endpoint to ensure the server is running.
 * @access  Public
 */
app.get('/api/health', (req, res) => {
  res.status(200).json({ 
    status: 'UP', 
    message: 'ALT-AI-MATE server is running smoothly.',
    dbStatus: 'Not Available (using mock data)'
  });
});

/**
 * @route   POST /api/projects
 * @desc    Create a new project
 * @access  Public
 */
app.post('/api/projects', (req, res) => {
    const { name, projectType, userId } = req.body;
    console.log('Received new project:', { name, projectType, userId });
    
    if (!name || !projectType) {
      return res.status(400).json({ error: 'Missing required fields: name and projectType' });
    }
    
    const newProject = {
        id: `proj_${Date.now()}`,
        name,
        project_type: projectType,
        user_id: userId || 'anonymous',
        created_at: new Date().toISOString(),
        status: 'Created'
    };
    
    res.status(201).json({ 
        message: 'Project created successfully', 
        project: newProject 
    });
});

/**
 * @route   POST /api/generate-code
 * @desc    Generates sample code based on a prompt.
 * @access  Public
 */
app.post('/api/generate-code', (req, res) => {
  const { prompt, projectType } = req.body;
  console.log('Code generation requested:', { prompt, projectType });

  if (!prompt || !projectType) {
    return res.status(400).json({ error: 'Missing required fields: prompt and projectType' });
  }

  // In a real app, a more sophisticated generation logic would be here.
  // For now, we'll generate a simple template that includes the user's prompt.
  const sampleCode = `// Generated ${projectType} app based on: ${prompt}
import React from 'react';

function App() {
  return (
    <div>
      <h1>Your ${projectType} App: ${prompt}</h1>
      <p>This is a sample component generated by ALT-AI-MATE.</p>
      <button onClick={() => alert('Hello from your generated app!')}>
        Click me!
      </button>
    </div>
  );
}

export default App;`;

  // Simulate network and processing time
  setTimeout(() => {
    res.status(200).json({ code: sampleCode });
  }, 1200);
});

// --- Server Initialization ---
const host = process.env.NODE_ENV === 'production' ? '0.0.0.0' : 'localhost';
app.listen(port, host, () => {
  console.log(`🚀 ALT-AI-MATE backend server is listening at http://${host}:${port}`);
  console.log(`Environment: ${process.env.NODE_ENV || 'development'}`);
});